fastscore:
  fleet:
    - api: model-manage
      host: model-manage
      port: 8002
    - api: engine
      host: engine-1
      port: 8003
    - api: engine
      host: engine-2
      port: 8003

  db:
    type: git
    url: https://github.com/brenstenkelly/backitup.git 
    branch: master
    username: brenstenkelly 
    password: ODG4evaeva

  pneumo:
    type: REST
    #type: kafka
    #bootstrap:
    #  - kafka:9092
    #topic: notify
