version: '3.3'

services:
  dashboard:
    image: fastscore/dashboard:1.10
    ports:
        - "8000:8000"
    environment:
      CONNECT_PREFIX: https://connect:8001
      BASE_PATH: ""
    networks:
      - fsnet

  connect:
    image: fastscore/connect:1.10
    ports:
        - "8001:8001"
    stdin_open: true
    tty: true
    networks:
      - fsnet

  engine-1:
    image: fastscore/engine:xgboost
    ports:
        - "8003:8003"
    volumes:
      - ./data:/data
    environment:
        CONNECT_PREFIX: https://connect:8001
    networks:
      - fsnet

  engine-2:
    image: fastscore/engine:linearexample
    volumes:
      - ./data:/data
    environment:
        CONNECT_PREFIX: https://connect:8001
    networks:
      - fsnet

  database:
    image: fastscore/model-manage-mysql:1.9
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - fsnet

  model-manage:
    image: fastscore/model-manage:1.10 
    depends_on:
      - connect
      - database
    environment:
      CONNECT_PREFIX: https://connect:8001
    networks:
      - fsnet

  kafka:
    image: fastscore/kafka:1.9
    ports:
      - "9092:9092"
    networks:
      - fsnet

volumes:
  db-data:

networks:
  fsnet:
