# This manifest creates any required PersistentVolumeClaims
# which are used, by default, to back the grafana/viz and airflow/scheduler metadata databases
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viz-disk
  labels:
    stack: fastscore
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ${ENV_STORAGECLASS_NAME}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-disk
  labels:
    stack: fastscore
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ${ENV_STORAGECLASS_NAME}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lineage-disk
  labels:
    stack: fastscore
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ${ENV_STORAGECLASS_NAME}
  resources:
    requests:
      storage: 1Gi
